### ISSUE TITLE
App design

### ISSUE THREAD

**Issue by Nagellan** [ElBatanony/innopolis_feedback#12]
* Think about the user journey and functionality
* Draw sketch
* Create layout at Figma using [Flutter UI kit](https://www.figma.com/resources/assets/material-design-themeing-ui-kit/)

**Comment by johnnthough** [comment]
hello i am interested in contributing

**Comment by Nagellan** [comment]
https://www.figma.com/file/wgfgt38jwJFMBtuwuqpM09/TA-Feedback-App?node-id=2%3A5814
